# Generated by Django 5.1.2 on 2024-11-01 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_delete_examscore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer',
            new_name='option_a',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option1',
            new_name='option_b',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option2',
            new_name='option_c',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='option3',
            new_name='option_d',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option4',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1),
            preserve_default=False,
        ),
    ]
